GET http://localhost:5000/items/

###

POST http://localhost:5000/items/
Content-Type: application/json

{
    "xauthtoken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNDdmMmY4MmE1ZDJiNDdkODZkMGE3MCIsImlhdCI6MTU4MTc3NTM1OCwiZXhwIjoxNTgxNzc4OTU4fQ.uTeu3SyxJkpF6dJphgLkD6h2DVHVRpq2BAzyrXNn730",
    "name": "Sleeping Bag"
}

###

DELETE http://localhost:5000/items/5e31655d29e78b1024bc4a47


###

GET http://localhost:5000/auth/user
Content-Type: application/json

{
    "xauthtoken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNDdlYzEzMmI3YTdjMTA5MDUxYzczZiIsImlhdCI6MTU4MTc3NTkwOSwiZXhwIjoxNTgxNzc5NTA5fQ.crjOalmfk3G2WOweQz-4JTlKbHCiDcxJZ0qO5O0nCZE"
}


###

POST http://localhost:5000/users/
Content-Type: application/json

{
    "name": "Mickey Donvan",
    "email": "mickeydonvan@gmail.com",
    "password": "password"
}


###

POST http://localhost:5000/auth/
Content-Type: application/json

{
    "email": "raydonvan@gmail.com",
    "password": "password"
}


