GET http://localhost:5000/items/

###

POST http://localhost:5000/items/
Content-Type: application/json

{
    "name": "Coffee Beans"
}

###

DELETE http://localhost:5000/items/5e31655d29e78b1024bc4a47


###

POST http://localhost:5000/users/
Content-Type: application/json

{
    "name": "Ray Donvan",
    "email": "raydonvan@gmail.com",
    "password": "password"
}
